### ISSUE TITLE
FATAL EXCEPTION: main

### ISSUE THREAD

**Issue by mehdico** [nexron171/SimVirtualLocation#1]
It's not working on android 13.

```
E/AndroidRuntime(21263): FATAL EXCEPTION: main
E/AndroidRuntime(21263): Process: com.devnex.simvirtuallocation, PID: 21263
E/AndroidRuntime(21263): java.lang.RuntimeException: Error receiving broadcast Intent { act=send.mock flg=0x400010 (has extras) } in com.devnex.simvirtuallocation.AdbBroadcastReceiver@369fe1
E/AndroidRuntime(21263): 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1928)
E/AndroidRuntime(21263): 	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
E/AndroidRuntime(21263): 	at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime(21263): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(21263): 	at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime(21263): 	at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(21263): 	at android.app.ActivityThread.main(ActivityThread.java:8757)
E/AndroidRuntime(21263): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(21263): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/AndroidRuntime(21263): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
E/AndroidRuntime(21263): Caused by: java.lang.IllegalArgumentException: gps provider is not a test provider
E/AndroidRuntime(21263): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3027)
E/AndroidRuntime(21263): 	at android.os.Parcel.createException(Parcel.java:3007)
E/AndroidRuntime(21263): 	at android.os.Parcel.readException(Parcel.java:2990)
E/AndroidRuntime(21263): 	at android.os.Parcel.readException(Parcel.java:2932)
E/AndroidRuntime(21263): 	at android.location.ILocationManager$Stub$Proxy.setTestProviderLocation(ILocationManager.java:2239)
E/AndroidRuntime(21263): 	at android.location.LocationManager.setTestProviderLocation(LocationManager.java:2144)
E/AndroidRuntime(21263): 	at com.devnex.simvirtuallocation.MockLocationProvider.pushLocation(MockLocationProvider.java:45)
E/AndroidRuntime(21263): 	at com.devnex.simvirtuallocation.AdbBroadcastReceiver.onReceive(AdbBroadcastReceiver.java:49)
E/AndroidRuntime(21263): 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1918)
E/AndroidRuntime(21263): 	... 9 more
E/AndroidRuntime(21263): Caused by: android.os.RemoteException: Remote stack trace:
E/AndroidRuntime(21263): 	at com.android.server.location.provider.LocationProviderManager.setMockProviderLocation(LocationProviderManager.java:1724)
E/AndroidRuntime(21263): 	at com.android.server.location.LocationManagerService.setTestProviderLocation(LocationManagerService.java:1858)
E/AndroidRuntime(21263): 	at android.location.ILocationManager$Stub.onTransact(ILocationManager.java:1181)
E/AndroidRuntime(21263): 	at android.os.Binder.execTransactInternal(Binder.java:1316)
E/AndroidRuntime(21263): 	at android.os.Binder.execTransact(Binder.java:1280)
```

**Comment by nexron171** [comment]
did you select SimVirtualLocation as Location Mocking tool in developer settings?
`Caused by: java.lang.IllegalArgumentException: gps provider is not a test provider`
