### ISSUE TITLE
Short distance mocking only

### ISSUE THREAD

**Issue by ieaksu** [nexron171/SimVirtualLocation#6]
Hey! First of all, thank you for this amazing tool! It works well with my iOS 17.2. But, simulation works only for shorter distances. If I set a distance longer than 6-7 blocks it stops mocking on the phone while the app on the mac still looks like it is proceeding. Also, after a couple of attempts I receive an error as shown in the screenshot that I'm attaching. Thank you again!
<img width="525" alt="Screenshot 2023-12-24 at 3 43 19 PM" src="https://github.com/nexron171/SimVirtualLocation/assets/154739221/4708a92e-ebc6-4663-8b5c-14bcda275976">

**Comment by nexron171** [comment]
Hi! Thanks for reporting the problem, I don’t know what caused this error yet, but I’ll try to experiment with possible solutions

**Comment by jechen922** [comment]
Hello, thank you for providing this amazing tool. I have encountered the same issue, and the complete error message is as follows. I hope it can help you solve the problem.

```
Traceback (most recent call last):
File "/opt/homebrew/bin/pymobiledevice3", line 8, in <module>
sys.exit(main())
^^^^^^
File "/Users/somebody/anaconda3/lib/python3.11/site-packages/pymobiledevice3/__main__.py", line 98, in main
cli()
File "/Users/somebody/anaconda3/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
return self.main(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/somebody/anaconda3/lib/python3.11/site-packages/click/core.py", line 1078, in main
rv = self.invoke(ctx)
^^^^^^^^^^^^^^^^
File "/Users/somebody/anaconda3/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/somebody/anaconda3/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/somebody/anaconda3/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Previous line repeated 1 more time]
File "/Users/somebody/anaconda3/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
return ctx.invoke(self.callback, **ctx.params)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/somebody/anaconda3/lib/python3.11/site-packages/click/core.py", line 783, in invoke
return __callback(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/somebody/anaconda3/lib/python3.11/site-packages/pymobiledevice3/cli/cli_common.py", line 159, in wrap_callback_calling
callback(service_provider=service_provider, **kwargs)
File "/Users/somebody/anaconda3/lib/python3.11/site-packages/pymobiledevice3/cli/developer.py", line 1014, in dvt_simulate_location_set
with DvtSecureSocketProxyService(service_provider) as dvt:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/somebody/anaconda3/lib/python3.11/site-packages/pymobiledevice3/services/dvt/dvt_secure_socket_proxy.py", line 24, in __init__
super().__init__(lockdown, service_name, remove_ssl_context=remove_ssl_context)
File "/Users/somebody/anaconda3/lib/python3.11/site-packages/pymobiledevice3/services/remote_server.py", line 362, in __init__
super().__init__(lockdown, service_name, is_developer_service=is_developer_service)
File "/Users/somebody/anaconda3/lib/python3.11/site-packages/pymobiledevice3/services/lockdown_service.py", line 20, in __init__
service = start_service(service_name, include_escrow_bag=include_escrow_bag)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/somebody/anaconda3/lib/python3.11/site-packages/pymobiledevice3/lockdown_service_provider.py", line 41, in start_lockdown_developer_service
return self.start_lockdown_service(name, include_escrow_bag=include_escrow_bag)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/somebody/anaconda3/lib/python3.11/site-packages/pymobiledevice3/lockdown.py", line 87, in _inner_reconnect_on_remote_close
return f(*args, **kwargs)
^^^^^^^^^^^^^^^^^^
File "/Users/somebody/anaconda3/lib/python3.11/site-packages/pymobiledevice3/lockdown.py", line 471, in start_lockdown_service
service_connection.ssl_start(f)
File "/Users/somebody/anaconda3/lib/python3.11/site-packages/pymobiledevice3/service_connection.py", line 176, in ssl_start
self.socket = create_context(certfile, keyfile=keyfile).wrap_socket(self.socket)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/somebody/anaconda3/lib/python3.11/ssl.py", line 517, in wrap_socket
return self.sslsocket_class._create(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/somebody/anaconda3/lib/python3.11/ssl.py", line 1054, in _create
self.getpeername()
OSError: [Errno 22] Invalid argument
```

Additionally, I have encountered another issue. At the beginning of 「simulate from A to B」, the location first jumps back to the actual position before returning to point A for the simulated movement.
I wonder if this part can also be resolved.
Thank you!!
